coat:
  CMICausE-CTR:
    alpha1: 0.01
    batch_size: 64
    beta2: 1.0e-05
    eps: 0.01
    k: 7
    l2_norm: 1.0e-05
    lamb: 0.001
    learning_rate: 0.0001
  CMIDR-CTR:
    batch_size: 32
    beta1: 0.012163079241333231
    beta2: 0.0001
    eps: 0.5
    k: 20
    l2_norm: 0.001
    lamb: 1
    learning_rate: 0.0003
  CMIDRJL-CTR:
    batch_size: 32
    beta1: 0.9753332364493128
    beta2: 1
    eps: 0.1
    k: 1
    l2_norm: 0.001
    lamb: 0.1
    learning_rate: 0.001
  CMIIDIPS-CTR:
    batch_size: 32
    beta1: 0.01182940560551223
    beta2: 10
    eps: 0.1
    k: 3
    l2_norm: 0.0001
    lamb: 0.0001
    learning_rate: 0.0001
  CMIIPS-CTR:
    batch_size: 32
    beta2: 10
    eps: 0.1
    k: 20
    l2_norm: 0.001
    lamb: 0.0001
    learning_rate: 0.0001
  CMIUDIPS-CTR:
    batch_size: 32
    beta1: 0.2658500049011801
    beta2: 10
    eps: 7
    k: 10
    l2_norm: 3.0e-05
    lamb: 0.001
    learning_rate: 3.0e-05
  CausE-CTR:
    alpha1: 0.0001
    batch_size: 16
    l2_norm: 0.0001
    learning_rate: 1.0e-05
  DR-CTR:
    beta1: 0.9383932893334295
    bsize: 64
    l2: 0.001
    lr: 0.0003
  DRJL-CTR:
    beta1: 0.9333710078137559
    bsize: 64
    l2: 0.0003
    lr: 0.0001
  FWDR-CTR:
    beta1: 0.9997261543810179
    beta2: 0.003
    bsize: 32
    l2: 0.001
    lr: 0.0003
  FWDRJL-CTR:
    beta1: 0.9303242315609902
    beta2: 5
    bsize: 64
    l2: 0.001
    lr: 0.0001
  FWIPS-CTR:
    beta2: 0.3
    bsize: 64
    l2: 1.0e-06
    lr: 0.001
  FWTJR-CTR:
    alpha1: 0.09772454833808408
    alpha2: 0.1
    beta2: 1
    bsize: 16
    l2: 0.0003
    lr: 0.0003
  FWUDIPS-CTR:
    beta1: 0.2933945804465394
    beta2: 1
    bsize: 32
    l2: 0.0001
    lr: 0.0003
  IDIPS-CTR:
    beta1: 0.7300916034056658
    bsize: 32
    l2: 0.001
    lr: 0.0003
  IPS-CTR:
    bsize: 64
    l2: 0.001
    lr: 0.0001
  TJR-CTR:
    alpha1: 0.01117984184889991
    alpha2: 0.5
    bsize: 32
    l2: 1.0e-05
    lr: 0.0003
  UDIPS-CTR:
    beta1: 0.2923287137237879
    bsize: 16
    l2: 3.0e-06
    lr: 0.0001
  bias_BASE-CTR:
    batch_size: 32
    l2_norm: 1.0e-05
    learning_rate: 0.0003
  bias_BASE1-CTR:
    alpha: 0.3
    batch_size: 32
    l2_norm: 3.0e-05
    learning_rate: 0.0003
    p: 8
    t: 0.001
  bias_BASE2-CTR:
    alpha: 0.1
    batch_size: 64
    beta: 0.03
    l2_norm: 0.0003
    lam: 1.0e-06
    learning_rate: 3.0e-05
    p: 2
    t: 0.9
  bias_BRIDGE-CTR:
    alpha1: 1
    batch_size: 64
    l2_norm: 3.0e-06
    learning_rate: 0.001
  bias_Bridge-CTR:
    alpha1: 1
    batch_size: 32
    l2_norm: 0.001
    learning_rate: 0.0003
  bias_CAUSE-CTR:
    alpha1: 1.0e-05
    batch_size: 64
    l2_norm: 3.0e-05
    learning_rate: 0.001
  bias_CMIABSTUDY-CTR:
    alpha1: 0.01
    alpha2: 0.1
    batch_size: 32
    beta1: 3
    k: 3
    l2_norm: 0.0003
    learning_rate: 0.0003
  bias_CMIBASE-CTR:
    batch_size: 32
    beta1: 5
    eps: 0.1
    k: 10
    l2_norm: 0.01
    lamb: 1.0e-05
    learning_rate: 0.0001
  bias_CMIBridge-CTR:
    alpha1: 0.1
    batch_size: 32
    beta2: 0.001
    eps: 9
    k: 3
    l2_norm: 0.001
    lamb: 1.0e-05
    learning_rate: 0.0003
  bias_CMIRefine-CTR:
    batch_size: 64
    beta1: 0.1113075737905913
    beta2: 0.1
    eps: 0.1
    k: 3
    l2_norm: 0.001
    lamb: 0.001
    learning_rate: 0.0003
  bias_CMITJR-CTR:
    alpha1: 0.07119942327619139
    alpha2: 0.4
    batch_size: 64
    beta1: 10
    eps: 0.1
    k: 5
    l2_norm: 0.003
    lamb: 0.1
    learning_rate: 3.0e-05
  bias_CausE-CTR:
    alpha1: 0.0001
    batch_size: 16
    l2_norm: 3.0e-06
    learning_rate: 0.0001
  bias_DR-CTR:
    batch_size: 16
    beta1: 0.9095582421891764
    l2_norm: 3.0e-05
    learning_rate: 1.0e-05
  bias_DRJL-CTR:
    batch_size: 64
    beta1: 0.4223710247621827
    l2_norm: 3.0e-06
    learning_rate: 0.001
  bias_FWBridge-CTR:
    alpha1: 1.0e-05
    beta2: 1
    bsize: 64
    l2: 0.001
    lr: 1.0e-05
  bias_FWRefine-CTR:
    beta1: 0.543179878703577
    beta2: 0.03
    bsize: 32
    l2: 1.0e-06
    lr: 0.001
  bias_IDIPS-CTR:
    batch_size: 16
    beta1: 0.08875006309792412
    l2_norm: 0.01
    learning_rate: 3.0e-05
  bias_IPS-CTR:
    batch_size: 64
    l2_norm: 1.0e-06
    learning_rate: 3.0e-05
  bias_MOE2-CTR:
    alpha: 0.0001
    batch_size: 16
    l2_norm: 0.001
    learning_rate: 0.0001
  bias_REFINE-CTR:
    batch_size: 32
    beta1: 0.8688545806157931
    l2_norm: 0.0001
    learning_rate: 0.0001
  bias_Refine-CTR:
    batch_size: 32
    beta1: 0.8688545806157931
    l2_norm: 0.0001
    learning_rate: 0.0001
  bias_TJR-CTR:
    alpha1: 0.06115735107432066
    alpha2: 0.3
    batch_size: 16
    l2_norm: 0.0003
    learning_rate: 0.0003
  bias_UDIPS-CTR:
    batch_size: 16
    beta1: 0.432325011697154
    l2_norm: 0.001
    learning_rate: 0.0003
  combine_BASE-CTR:
    batch_size: 16
    l2_norm: 3.0e-05
    learning_rate: 0.0003
  combine_BASE1-CTR:
    alpha: 1
    batch_size: 32
    l2_norm: 0.001
    learning_rate: 0.0003
    p: 4
    t: 0.01
  combine_BASE2-CTR:
    alpha: 0.1
    batch_size: 16
    beta: 0.0003
    l2_norm: 0.0003
    lam: 0.1
    learning_rate: 0.0001
    p: 4
    t: 1
  combine_CMIABSTUDY-CTR:
    batch_size: 32
    beta1: 1.0e-05
    eps: 5
    k: 5
    l2_norm: 0.001
    lamb: 0.1
    learning_rate: 0.0001
  combine_CMIBASE-CTR:
    batch_size: 32
    beta1: 0.0001
    eps: 5
    k: 20
    l2_norm: 0.003
    lamb: 0.01
    learning_rate: 0.0001
  combine_MOE2-CTR:
    alpha: 0.03
    batch_size: 32
    l2_norm: 3.0e-05
    learning_rate: 0.0003
  unif_BASE-CTR:
    batch_size: 32
    l2_norm: 0.0003
    learning_rate: 0.001
