kuairand:
  CMICausE-CTR:
    alpha1: 1.0e-05
    batch_size: 1024
    beta2: 1.0e-05
    eps: 1
    k: 3
    l2_norm: 0.001
    lamb: 0.1
    learning_rate: 3.0e-05
  CMIDR-CTR:
    batch_size: 128
    beta1: 0.416585156221423
    beta2: 1.0e-05
    eps: 50
    k: 7
    l2_norm: 0.001
    lamb: 1.0e-05
    learning_rate: 3.0e-05
  CMIDRJL-CTR:
    batch_size: 1024
    beta1: 0.23544714433844005
    beta2: 5
    eps: 100
    k: 7
    l2_norm: 0.0003
    lamb: 1
    learning_rate: 3.0e-05
  CMIIDIPS-CTR:
    batch_size: 1024
    beta1: 0.010436311924771768
    beta2: 1.0e-05
    eps: 50
    k: 7
    l2_norm: 1.0e-06
    lamb: 0.0001
    learning_rate: 0.001
  CMIIPS-CTR:
    batch_size: 256
    beta2: 0.1
    eps: 0.5
    k: 3
    l2_norm: 3.0e-05
    lamb: 1.0e-05
    learning_rate: 0.0003
  CMITJR-CTR:
    alpha1: 0.09995576563442103
    alpha2: 1
    batch_size: 512
    beta1: 1.0e-05
    eps: 10
    k: 3
    l2_norm: 0.0001
    lamb: 0.01
    learning_rate: 3.0e-05
  CMIUDIPS-CTR:
    batch_size: 256
    beta1: 0.5115948576349936
    beta2: 0.0001
    eps: 100
    k: 7
    l2_norm: 0.0003
    lamb: 0.1
    learning_rate: 3.0e-05
  CausE-CTR:
    alpha1: 1
    batch_size: 1024
    l2_norm: 0.001
    learning_rate: 3.0e-05
  DR-CTR:
    beta1: 0.16200827336135237
    bsize: 512
    l2: 3.0e-05
    lr: 0.0001
  DRJL-CTR:
    beta1: 0.2758183148040221
    bsize: 512
    l2: 0.001
    lr: 3.0e-05
  FWDR-CTR:
    beta1: 0.2491024905138061
    beta2: 300.0
    bsize: 256
    l2: 3.0e-06
    lr: 0.001
  FWDRJL-CTR:
    beta1: 0.021842592710952985
    beta2: 300.0
    bsize: 256
    l2: 1.0e-05
    lr: 0.0001
  FWIPS-CTR:
    beta2: 3.0e-05
    bsize: 256
    l2: 0.0003
    lr: 3.0e-05
  FWTJR-CTR:
    alpha1: 0.09818612601363036
    alpha2: 0.1
    beta2: 100.0
    bsize: 512
    l2: 0.0001
    lr: 1.0e-05
  FWUDIPS-CTR:
    beta1: 0.31686899282962444
    beta2: 0.0003
    bsize: 256
    l2: 0.001
    lr: 1.0e-05
  IDIPS-CTR:
    beta1: 0.01108109740778112
    bsize: 512
    l2: 0.001
    lr: 1.0e-05
  IPS-CTR:
    bsize: 256
    l2: 0.0003
    lr: 3.0e-05
  TJR-CTR:
    alpha1: 0.09997798813297237
    alpha2: 0.2
    bsize: 512
    l2: 0.001
    lr: 1.0e-05
  UDIPS-CTR:
    beta1: 0.36663314928588936
    bsize: 256
    l2: 0.001
    lr: 1.0e-05
  bias_BASE-CTR:
    batch_size: 256
    l2_norm: 0.001
    learning_rate: 1.0e-05
  bias_BASE1-CTR:
    alpha: 7
    batch_size: 2048
    l2_norm: 0.001
    learning_rate: 3.0e-05
    p: 4
    t: 0.001
  bias_BASE2-CTR:
    alpha: 3
    batch_size: 256
    beta: 5
    l2_norm: 0.001
    lam: 0.01
    learning_rate: 3.0e-05
    p: 32
    t: 0.001
  bias_CMIABSTUDY-CTR:
    alpha1: 0.0001
    alpha2: 5
    batch_size: 256
    beta1: 5
    k: 3
    l2_norm: 0.0003
    learning_rate: 3.0e-05
  bias_CMIBASE-CTR:
    batch_size: 256
    beta1: 0.1
    eps: 0.001
    k: 5
    l2_norm: 0.0003
    lamb: 0.1
    learning_rate: 3.0e-05
  bias_CMIBridge-CTR:
    alpha1: 0.01
    batch_size: 256
    beta2: 5
    eps: 100
    k: 10
    l2_norm: 3.0e-06
    lamb: 1
    learning_rate: 3.0e-05
  bias_CMIRefine-CTR:
    batch_size: 1024
    beta1: 0.9668570373065533
    beta2: 1
    eps: 0.1
    k: 20
    l2_norm: 1.0e-06
    lamb: 0.0001
    learning_rate: 1.0e-05
  bias_CMITJR-CTR:
    alpha1: 0.04651835864249725
    alpha2: 1.0
    batch_size: 512
    beta1: 10
    eps: 0.5
    k: 10
    l2_norm: 0.01
    lamb: 0.0001
    learning_rate: 1.0e-05
  bias_FWBridge-CTR:
    alpha1: 0.1
    beta2: 5
    bsize: 256
    l2: 1.0e-06
    lr: 0.0001
  bias_FWRefine-CTR:
    beta1: 0.9416337186804771
    beta2: 10
    bsize: 512
    l2: 0.001
    lr: 0.0003
  bias_MOE2-CTR:
    alpha: 0.003
    batch_size: 256
    l2_norm: 0.0003
    learning_rate: 3.0e-05
  combine_BASE-CTR:
    batch_size: 256
    l2_norm: 0.001
    learning_rate: 1.0e-05
  combine_BASE1-CTR:
    alpha: 10
    batch_size: 1024
    l2_norm: 0.001
    learning_rate: 1.0e-05
    p: 128
    t: 0.0001
  combine_BASE2-CTR:
    alpha: 7
    batch_size: 256
    beta: 0.01
    l2_norm: 0.001
    lam: 1.0e-05
    learning_rate: 3.0e-06
    p: 8
    t: 1.0e-05
  combine_CMIABSTUDY-CTR:
    batch_size: 128
    beta1: 0.01
    eps: 1
    k: 3
    l2_norm: 0.003
    lamb: 0.01
    learning_rate: 1.0e-05
  combine_CMIBASE-CTR:
    batch_size: 1024
    beta1: 10
    eps: 100
    k: 20
    l2_norm: 0.001
    lamb: 1.0e-05
    learning_rate: 1.0e-05
  combine_MOE2-CTR:
    alpha: 0.01
    batch_size: 512
    l2_norm: 0.001
    learning_rate: 1.0e-05
  unif_BASE-CTR:
    batch_size: 1024
    l2_norm: 0.001
    learning_rate: 0.0001
