coat:
  CMICausE-CTR:
    alpha1: 0.01
    batch_size: 64
    beta2: 0.1
    eps: 0.1
    k: 20
    l2_norm: 1.0e-06
    lamb: 1
    learning_rate: 0.0001
  CMIDR-CTR:
    batch_size: 64
    beta1: 0.27015520865609816
    beta2: 1
    eps: 9
    k: 7
    l2_norm: 0.001
    lamb: 1
    learning_rate: 0.001
  CMIDRJL-CTR:
    batch_size: 64
    beta1: 0.624714998324109
    beta2: 5
    eps: 0.1
    k: 10
    l2_norm: 0.0001
    lamb: 1.0e-05
    learning_rate: 3.0e-05
  CMIIDIPS-CTR:
    batch_size: 64
    beta1: 0.0942024547946365
    beta2: 1
    eps: 0.1
    k: 10
    l2_norm: 3.0e-05
    lamb: 0.01
    learning_rate: 3.0e-05
  CMIIPS-CTR:
    batch_size: 64
    beta2: 10
    eps: 0.1
    k: 7
    l2_norm: 0.0003
    lamb: 0.0001
    learning_rate: 0.0001
  CMIUDIPS-CTR:
    batch_size: 16
    beta1: 0.2628706542061816
    beta2: 0.001
    eps: 5
    k: 20
    l2_norm: 3.0e-05
    lamb: 1.0e-05
    learning_rate: 0.0001
  CausE-CTR:
    alpha1: 0.001
    batch_size: 32
    l2_norm: 0.0001
    learning_rate: 0.001
  DR-CTR:
    beta1: 0.9959092795930122
    bsize: 16
    l2: 0.001
    lr: 0.0001
  DRJL-CTR:
    beta1: 0.9772089479296431
    bsize: 32
    l2: 0.001
    lr: 0.0001
  FWDR-CTR:
    beta1: 0.9454864965477388
    beta2: 3.0e-05
    bsize: 32
    l2: 0.001
    lr: 0.0001
  FWDRJL-CTR:
    beta1: 0.983305054492861
    beta2: 0.003
    bsize: 32
    l2: 0.0001
    lr: 0.0003
  FWIPS-CTR:
    beta2: 10
    bsize: 64
    l2: 3.0e-06
    lr: 0.0003
  FWTJR-CTR:
    alpha1: 0.03925828276160858
    alpha2: 0.2
    beta2: 5
    bsize: 32
    l2: 1.0e-05
    lr: 0.0003
  FWUDIPS-CTR:
    beta1: 0.2989951063769649
    beta2: 1
    bsize: 32
    l2: 1.0e-05
    lr: 0.0003
  IDIPS-CTR:
    beta1: 0.8608617585204235
    bsize: 32
    l2: 0.001
    lr: 0.0001
  IPS-CTR:
    bsize: 64
    l2: 0.0003
    lr: 0.0003
  TJR-CTR:
    alpha1: 0.07726830472221535
    alpha2: 0.3
    bsize: 64
    l2: 0.001
    lr: 0.0003
  UDIPS-CTR:
    beta1: 0.5328238222418207
    bsize: 16
    l2: 0.0001
    lr: 0.0001
  bias_BASE-CTR:
    batch_size: 32
    l2_norm: 0.0003
    learning_rate: 0.0001
  bias_BASE1-CTR:
    alpha: 0.003
    batch_size: 16
    l2_norm: 0.0003
    learning_rate: 0.0001
    p: 1
    t: 0.1
  bias_BASE2-CTR:
    alpha: 0.3
    batch_size: 32
    beta: 3.0e-05
    l2_norm: 3.0e-05
    lam: 0.03
    learning_rate: 0.0003
    p: 1
    t: 0.9
  bias_CMIABSTUDY-CTR:
    alpha1: 0.0001
    alpha2: 5
    batch_size: 32
    beta1: 0.1
    k: 3
    l2_norm: 0.003
    learning_rate: 3.0e-05
  bias_CMIBASE-CTR:
    batch_size: 16
    beta1: 10
    eps: 0.0001
    k: 1
    l2_norm: 0.001
    lamb: 0.1
    learning_rate: 1.0e-05
  bias_CMIBridge-CTR:
    alpha1: 1
    batch_size: 64
    beta2: 5
    eps: 0.1
    k: 7
    l2_norm: 1.0e-06
    lamb: 0.01
    learning_rate: 1.0e-05
  bias_CMIRefine-CTR:
    batch_size: 16
    beta1: 0.24613771594245087
    beta2: 5
    eps: 7
    k: 5
    l2_norm: 0.0003
    lamb: 1
    learning_rate: 0.0003
  bias_CMITJR-CTR:
    alpha1: 0.06678233028417639
    alpha2: 0.3
    batch_size: 64
    beta1: 1.0e-05
    eps: 3
    k: 3
    l2_norm: 3.0e-05
    lamb: 0.0001
    learning_rate: 0.0001
  bias_FWBridge-CTR:
    alpha1: 1.0e-05
    beta2: 5
    bsize: 64
    l2: 1.0e-06
    lr: 0.0003
  bias_FWRefine-CTR:
    beta1: 0.5029227889805955
    beta2: 0.1
    bsize: 32
    l2: 0.0003
    lr: 0.0003
  bias_MOE2-CTR:
    alpha: 3.0e-05
    batch_size: 16
    l2_norm: 3.0e-05
    learning_rate: 0.0001
  combine_BASE-CTR:
    batch_size: 64
    l2_norm: 3.0e-06
    learning_rate: 0.001
  combine_BASE1-CTR:
    alpha: 0.0003
    batch_size: 16
    l2_norm: 1.0e-06
    learning_rate: 0.001
    p: 8
    t: 0.0001
  combine_BASE2-CTR:
    alpha: 0.3
    batch_size: 16
    beta: 0.003
    l2_norm: 1.0e-05
    lam: 1.0e-05
    learning_rate: 0.0003
    p: 4
    t: 0.1
  combine_CMIABSTUDY-CTR:
    batch_size: 64
    beta1: 1.0e-05
    eps: 3
    k: 7
    l2_norm: 3.0e-05
    lamb: 1.0e-05
    learning_rate: 3.0e-05
  combine_CMIBASE-CTR:
    batch_size: 32
    beta1: 1.0e-05
    eps: 3
    k: 20
    l2_norm: 1.0e-05
    lamb: 0.001
    learning_rate: 3.0e-05
  combine_MOE2-CTR:
    alpha: 0.0003
    batch_size: 16
    l2_norm: 0.0003
    learning_rate: 0.0001
  unif_BASE-CTR:
    batch_size: 16
    l2_norm: 0.0001
    learning_rate: 0.001
